/**
 * 各類場所消防安全設備設置標準 — 導覽資料
 * pcode: D0120029
 * 法規修正：民國 113 年 04 月 24 日
 */
const LAW = {
  pcode: 'D0120029',
  name: '各類場所消防安全設備設置標準',
  amended: '民國 113 年 04 月 24 日',
  fullUrl: 'https://law.moj.gov.tw/LawClass/LawAll.aspx?pcode=D0120029',
  updated: '2026/09/15',
  author: 'AJ',
};

function mojArticleUrl(article) {
  const flno = String(article).replace(/\s+/g, '');
  return `https://law.moj.gov.tw/LawClass/LawSingle.aspx?pcode=${LAW.pcode}&flno=${encodeURIComponent(flno)}`;
}

const CATEGORIES = [
  {
    id: 'design',
    icon: '📋',
    title: '消防設計',
    subtitle: '設置義務',
    desc: '各類場所應設置之消防安全設備',
    articles: [
      { art: '14', label: '滅火器' },
      { art: '15', label: '室內消防栓' },
      { art: '16', label: '室外消防栓' },
      { art: '17', label: '自動撒水設備' },
      { art: '18', label: '水霧、泡沫、乾粉、CO₂' },
      { art: '19', label: '火警自動警報' },
      { art: '20', label: '手動報警' },
      { art: '21', label: '瓦斯警報' },
      { art: '22', label: '緊急廣播' },
      { art: '22-1', label: '119 通報裝置' },
      { art: '23', label: '標示設備' },
      { art: '24', label: '緊急照明' },
      { art: '25', label: '避難器具' },
      { art: '26', label: '連結送水' },
      { art: '27', label: '蓄水池' },
      { art: '28', label: '排煙設備' },
      { art: '29', label: '緊急插座' },
      { art: '30', label: '通信輔助' },
      { art: '30-1', label: '防災監控系統' },
    ],
  },
  {
    id: 'extinguisher',
    icon: '🧯',
    title: '滅火器',
    subtitle: '第 31 條 · 計算工具',
    desc: '滅火效能值核算與配置規範',
    calculators: ['extinguisher'],
    articles: [
      { art: '14', label: '設置義務' },
      { art: '31', label: '滅火器配置與標識' },
    ],
  },
  {
    id: 'hydrant',
    icon: '🚒',
    title: '室內外消防栓',
    subtitle: '第 32–42 條',
    desc: '配管、消防栓、水源及幫浦',
    articles: [
      { art: '32', label: '配管、屋頂水箱' },
      { art: '33', label: '壓力試驗' },
      { art: '34', label: '消防栓' },
      { art: '35', label: '栓箱' },
      { art: '36', label: '水源容量（室內）' },
      { art: '37', label: '幫浦（室內）' },
      { art: '38', label: '緊急電源' },
      { art: '39', label: '準用（電源）' },
      { art: '40', label: '室外栓設置' },
      { art: '41', label: '水源容量（室外）' },
      { art: '42', label: '幫浦（室外）' },
    ],
  },
  {
    id: 'sprinkler',
    icon: '💧',
    title: '自動撒水',
    subtitle: '第 46–60 條',
    desc: '撒水頭配置、位置及附屬設備',
    articles: [
      { art: '46', label: '撒水頭配置' },
      { art: '47', label: '撒水頭位置' },
      { art: '48', label: '標示溫度' },
      { art: '49', label: '免設撒水頭' },
      { art: '50', label: '撒水頭放水量' },
      { art: '51', label: '流水檢知裝置' },
      { art: '52', label: '開放式啟動' },
      { art: '53', label: '一齊開放閥' },
      { art: '54', label: '放水區域' },
      { art: '55', label: '乾式·預動式' },
      { art: '56', label: '末端查驗閥' },
      { art: '57', label: '輔助撒水栓' },
      { art: '58', label: '幫浦' },
      { art: '59', label: '送水口' },
      { art: '60', label: '預備電源' },
    ],
  },
  {
    id: 'foam',
    icon: '🫧',
    title: '泡沫設備',
    subtitle: '第 71–81 條',
    desc: '泡沫頭配置、放射及儲槽',
    articles: [
      { art: '71', label: '泡沫頭配置' },
      { art: '72', label: '泡沫頭放射量' },
      { art: '73', label: '高發泡放出口' },
      { art: '74', label: '準用規定' },
      { art: '75', label: '泡沫放射區域' },
      { art: '76', label: '水源' },
      { art: '77', label: '加壓送水裝置' },
      { art: '78', label: '泡沫原液儲量' },
      { art: '79', label: '混合濃度' },
      { art: '80', label: '移動式泡沫滅火設備' },
      { art: '81', label: '泡沫原液儲槽' },
    ],
  },
  {
    id: 'alarm',
    icon: '🔔',
    title: '火警自動警報',
    subtitle: '第 112–132 條',
    desc: '探測器、總機及警鈴設置',
    articles: [
      { art: '112', label: '火警分區' },
      { art: '113', label: '火警鳴動' },
      { art: '114', label: '探測器高度' },
      { art: '115', label: '探測器位置' },
      { art: '116', label: '免設探測器' },
      { art: '117', label: '偵煙式不得設' },
      { art: '118', label: '偵煙式設置' },
      { art: '119', label: '探測區域' },
      { art: '120', label: '差動式設置' },
      { art: '121', label: '分布型探測器' },
      { art: '122', label: '偵煙式裝置' },
      { art: '123', label: '光分離探測器' },
      { art: '124', label: '火焰式探測器' },
      { art: '125', label: '總機裝置' },
      { art: '126', label: '總機位置' },
      { art: '127', label: '配線' },
      { art: '128', label: '緊急電源' },
      { art: '129', label: '發信機設置' },
      { art: '130', label: '標示燈設置' },
      { art: '131', label: '警鈴設置' },
      { art: '132', label: '綜合盤設置' },
    ],
  },
  {
    id: 'broadcast',
    icon: '📢',
    title: '廣播設備',
    subtitle: '第 133–139 條',
    desc: '揚聲器、分區及配線',
    articles: [
      { art: '133', label: '揚聲器裝置' },
      { art: '134', label: '廣播分區' },
      { art: '135', label: '火警連動、預備電源' },
      { art: '136', label: '啟動裝置' },
      { art: '137', label: '遮斷' },
      { art: '138', label: '擴音機及操作裝置' },
      { art: '139', label: '廣播配線' },
    ],
  },
  {
    id: 'signage',
    icon: '🚪',
    title: '標示／照明',
    subtitle: '第 146、153、155–156、176–179 條',
    desc: '出口標示燈、避難指標及緊急照明',
    articles: [
      { art: '146', label: '免設標示燈' },
      { art: '146-1', label: '等級區分' },
      { art: '146-2', label: '有效範圍' },
      { art: '146-3', label: '設置位置' },
      { art: '146-4', label: '裝設規定' },
      { art: '146-5', label: '特殊及閃滅' },
      { art: '146-6', label: '觀眾席引導燈' },
      { art: '146-7', label: '常亮規定' },
      { art: '153', label: '避難指標位置' },
      { art: '155', label: '標示燈緊急電源' },
      { art: '156', label: '不得設開關' },
      { art: '176', label: '照明配線開關' },
      { art: '177', label: '照明緊急電源' },
      { art: '178', label: '照度' },
      { art: '179', label: '免設照明' },
    ],
  },
  {
    id: 'escape',
    icon: '🪜',
    title: '避難器具',
    subtitle: '第 157–174 條',
    desc: '緩降機、避難梯、救助袋及滑杆',
    articles: [
      { art: '157', label: '設置場所' },
      { art: '158', label: '減設規定' },
      { art: '159', label: '免設規定' },
      { art: '160', label: '收容人員計算' },
      { art: '161', label: '器具裝設' },
      { art: '162', label: '必要開口' },
      { art: '163', label: '操作面積' },
      { art: '164', label: '下降空間' },
      { art: '165', label: '下降空地' },
      { art: '166', label: '器具標示' },
      { art: '167', label: '緩降機設置' },
      { art: '168', label: '滑臺' },
      { art: '169', label: '避難橋' },
      { art: '170', label: '救助袋設置' },
      { art: '171', label: '避難梯設置' },
      { art: '172', label: '滑杆設置' },
      { art: '173', label: '支固器具' },
      { art: '174', label: '支固螺栓' },
    ],
  },
  {
    id: 'smoke',
    icon: '💨',
    title: '排煙設備',
    subtitle: '第 188、190 條 · 計算工具',
    desc: '風量、開口計算及防煙區劃規定',
    calculators: ['smoke'],
    articles: [
      { art: '188', label: '防煙區劃' },
      { art: '188', label: '排煙口', note: '同第 188 條第三款' },
      { art: '188', label: '預備電源', note: '同第 188 條第九款' },
      { art: '188', label: '手動及自動啟動', note: '同第 188 條第六款' },
      { art: '190', label: '免設排煙設備' },
    ],
  },
  {
    id: '119',
    icon: '📞',
    title: '119 火災通報',
    subtitle: '第 145-1 條',
    desc: '119 火災通報裝置設置規定',
    articles: [
      { art: '145-1', label: '119 火災通報裝置' },
    ],
  },
];
